### ISSUE TITLE
HL2RP Duplicating ' symbol

### ISSUE THREAD

**Issue by LightningDuck104** [CloudSixteen/Clockwork#246]
If a player has a ' symbol in their name or physical description, over time it will begin to duplicate and become '''''''''. Is there a known fix to this?

**Comment by CuddlyAngel** [comment]
It's a known issue with Clockwork, not sure the cause of it as of yet.

**Comment by Lv6** [comment]
It's usually due to an issue with the SQL database; I've found that when switching to a hosted server with a site built in, and having the SQL run off of that as opposed to the same box as the server, the issue stops.

**Comment by CuddlyAngel** [comment]
Oh-- That could help narrow things down, thanks for the info!

**Comment by VortixDev** [comment]
For those experiencing this, it's down to the fact that `Clockwork.database.Escape` uses `sql.SQLStr` when SQLite is used, which bounds its strings with single quotes versus Clockwork's use of double quotes. To escape any single quotes in the string, `sql.SQLStr` replaces one single quote with two. Since escaping single quotes is not necessary for the database library's SQL queries (due to the use of double quotes), the doubling of single quotes serves to double the amount of single quotes stored, rather than escape the single quotes.

As `Clockwork.database.Escape` is defined by CloudAuthX, I cannot push a fix to the repository, but I have released a plugin which resolves this: https://github.com/VortixDev/cw_plugins/blob/master/no_apostrophe_spam/plugin/sv_plugin.lua.

My fix just overrides  `Clockwork.database.Escape` and replaces any instance of two single quotes with one if SQLite is used. It also checks before overriding whether `Clockwork.database.Escape` suffers from the doubling issue, so that if a CAX fix is pushed there won't be any problems.

**Comment by VortixDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the duplicating apostrophes SQLite bug](https://trello.com/c/9jb2htEr/17-fix-the-duplicating-apostrophes-sqlite-bug)

**Comment by VortixDev** [comment]
This is now resolved within CAX.
