### ISSUE TITLE
Observer Glitching

### ISSUE THREAD

**Issue by cornpop37** [CloudSixteen/Clockwork#317]
So uh, whenever you go into observer, instead of going invisible you just kinda start blinking in and out. It makes it kinda weird to do admin sits and "spy" on people. Any idea of how to fix this?

**Comment by xRJx** [comment]
I'll need some answers to these questions to help you: Which version of Clockwork are you using? Are there any errors in your server's console log? Have you modified your version of Clockwork in any way? What did you do specifically that caused that issue?

If this issue is no longer relevant please let me know.
